### ISSUE TITLE
What to do next?

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#297]
I'm feeling pretty good about the current state of the `v300` branch.  Unfortunately, it's living in a repository that indicates that the template is for zc156 and its version is 2.0.0c.

Without @zcadditions around, since he owns the repository, it's not possible for me as a collaborator to change the repository's name.  Leaving this as-is will, IMO, cause major confusion since the v300 release's zip file will be named based on the repository's name.

Anyone have any suggestions?

**Comment by barco57** [comment]
I suppose you could run the v300 out of your GitHub account as its own project. I really feel that the bootstrap template needs someone who is going to be around. you probably want to change the @ rbarbour as that references a different github user, probably should be @zcadditions. If Ray turns up and is going to maintain the repository in the future he can start a new project based on the work you have done. He hasn't been on the forum since the middle of July and has lost his domain name, and that is just not workable as far as I am concerned.

**Comment by lat9** [comment]
My primary concern with 'taking over' is/was to keep the issue-tracking back to this 'parent' repository in place.  I see now that there's an option on forked repositories to have their 'own' issue tracking.  I'll need to play with that a bit to make sure that the issues are a 'union' of the fork and its parent.

**Comment by lat9** [comment]
OK, I've renamed my fork to be 'generic' and to identify the `v300` branch as the default (https://github.com/lat9/ZCA-Bootstrap-Template).  Issues are now enabled for that fork.

I'll be creating a pinned issue here to indicate that future updates will be made to the above fork and that this repository is, essentially, being retired.
